# Generated by Django 6.0.3 on 2026-04-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyokalut', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='returned_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
