# Generated by Django 6.0.3 on 2026-04-21 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyokalut', '0002_alter_loan_returned_at_alter_tool_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-borrowed_at']},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['name'], 'verbose_name_plural': 'Tools'},
        ),
    ]
