# Generated by Django 6.0.3 on 2026-04-27 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyokalut', '0003_alter_loan_options_alter_tool_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-borrowed_at'], 'verbose_name': 'laina', 'verbose_name_plural': 'Lainat'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'valmistaja', 'verbose_name_plural': 'Valmistajat'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'kategoria', 'verbose_name_plural': 'Kategoriat'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['name'], 'verbose_name': 'työkalu', 'verbose_name_plural': 'Työkalut'},
        ),
        migrations.AlterField(
            model_name='loan',
            name='borrowed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Lainauspäivä'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateTimeField(verbose_name='Eräpäivä'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='returned_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Palautettu'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tyokalut.tool', verbose_name='Työkalu'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Käyttäjä'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nimi'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nimi'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='acquisition_year',
            field=models.IntegerField(verbose_name='Hankintavuosi'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(verbose_name='Kuvaus'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tools/', verbose_name='Kuva'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='manufacturers',
            field=models.ManyToManyField(to='tyokalut.manufacturer', verbose_name='Valmistaja'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nimi'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tyokalut.tag', verbose_name='Kategoria'),
        ),
    ]
