# Generated by Django 6.0.3 on 2026-04-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyokalut', '0004_alter_loan_options_alter_manufacturer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='default_loan_days',
            field=models.PositiveIntegerField(default=14, help_text='Kuinka monta päivää tämän kategorian työkaluja saa yleensä lainata?', verbose_name='Oletuslaina-aika (päivää)'),
        ),
    ]
